### ISSUE TITLE
A problem occurred configuring project ':react-native-image-keyboard'. > com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

### ISSUE THREAD

**Issue by AmirDiafi** [Gustash/react-native-image-keyboard#26]
Gradle used => `gradle-7.2-all.zip`
React Native Version => `0.67.2`

**Comment by Gustash** [comment]
This issue does not have enough information.

Try v2.1.1, if that still doesn't work please open a new issue with more information.
