### ISSUE TITLE
Gradle 7 support

### ISSUE THREAD

**Issue by Abhishek2250** [Gustash/react-native-image-keyboard#31]
Hey,

There are two issues for gradle 7 support.

1. Plugin with id 'maven' not found. (maven has been changed to `maven-publish`)
2. compileSdkVersion is not specified. Please add it to build.gradle

Versions:
"react-native-image-keyboard": "^2.0.5",
"react-native": "^0.68.1"
gradle: 7.3.3

Thanks

**Comment by Gustash** [comment]
Hey, thanks for opening this issue. I'm aware that this package isn't working for 0.67+ right now. 

I'm currently dealing with getting another package of mine ready for 0.68, but as soon as I have that done I'll get this package 0.67+ ready 😄

**Comment by Abhishek2250** [comment]
Thanks for the quick response. :)

**Comment by Gustash** [comment]
@Abhishek2250 This should have been fixed on v2.1.1. Feel free to comment or re-open if you're still unable to build!
