### ISSUE TITLE
`TextInput` `secureTextEntry` doesn't work

### ISSUE THREAD

**Issue by ghost** [Gustash/react-native-image-keyboard#36]
After adding `react-native-image-keyboard` `secureTextEntry` on `TextInput` don't work.

```jsx
<TextInput
  style={themedStyle.border}
  onChangeText={onChange}
  onBlur={onBlur}
  value={value}
  secureTextEntry
  autoCapitalize="none"
  />
```

This works like normal text input field.

**Comment by 83wid** [comment]
I have the same issue

**Comment by matijevic-dragomir** [comment]
You should read past issues before opening new ones.

https://github.com/Gustash/react-native-image-keyboard/issues/7#issuecomment-714328960
The fix is to add `multiline={false}` prop to the `TextInput` component.
