### ISSUE TITLE
Can not block new line in textInput (Android)

### ISSUE THREAD

**Issue by HappyCodingLover** [Gustash/react-native-image-keyboard#6]
Hi, guys.
After I added this package, I can not block new line in Android. (not sure in iOS)
When I click return Key on keyboard,
Actual Result: It adds a new line in textInput.
Expected Result : It gets out of textInput.
RN: 0.62

The help would be very appriciated.

**Comment by sumitrana1996** [comment]
Use multiline={false} Prop in your TexInput
