### ISSUE TITLE
secureTextEntry props of TextInput does not work.

### ISSUE THREAD

**Issue by krupalikevadiya** [Gustash/react-native-image-keyboard#7]

**Comment by sumitrana1996** [comment]
Use multiline={false} Prop in your TexInput

**Comment by krupalikevadiya** [comment]
It's worked.Thank you.

**Comment by krupalikevadiya** [comment]
Hey @sumitrana1996 I got another issue in android can you please guide me how to resolve it?
Getting following error log when i select gif from keyboard in android.
https://prnt.sc/1rtb52y
