### ISSUE TITLE
LICENSE change

### ISSUE THREAD

**Issue by Gustash** [Gustash/react-native-image-keyboard#8]
I am planning to change the license of this project from the MIT license to the GPLv3 license. The main reason for this is my belief that all software should be free (free as in freedom, not as in free beer) because that empowers every user and curtails the possibility of monopolistic aproaches to software development.

Even though I am the owner and maintainer of this project, I believe in democracy everywhere and am not looking to be a "dictator" of sorts when it comes to managing this project. As such, I am setting a deadline at the end of the year (31st of December) to let you argument against this change and have you vote in whether this license change happens or not.

As such, if until the end of the year I have 30% of users which starred this project (11) by the time of this issue's creation (33) against this change, the license shall remain as MIT. I will count a vote in favour of this change as a 👍 reaction to this issue, and a vote against it as a 👎 . I would prefer if, when casting your vote, you comment on this issue as to why you voted for/against this decision.

As a clarification, I shall only count votes induvidually from companies, as to avoid large companies using the software having a major say over the community at large, so I shall discard any votes if I find them to be additional votes from a company's staff or from an account created after the posting of this issue.

If the license change ends up happening, this does not bar you from using versions currently licensed under MIT as such, but it will require you to comply to GPLv3 if using any version published after the change.

Thank you for understanding and for your input.

**Comment by Gustash** [comment]
License has now changed to GPLv3. As mentioned, you can keep using the MIT license as long as you use a version before 2.0.0

**Comment by ejain** [comment]
Looks like this package doesn't work with React Native 0.67.2? I'd file a bug report and maybe even contribute a fix, but since the app I'm working on isn't GPL'd (very few React Native apps are...), I'll have to pass 😢

**Comment by Gustash** [comment]
> Looks like this package doesn't work with React Native 0.67.2? I'd file a bug report and maybe even contribute a fix, but since the app I'm working on isn't GPL'd (very few React Native apps are...), I'll have to pass 😢 

@ejain I don't see how that's a problem? I won't go after you to release the code for your app, the most I'd do is request access to the code to debug if you're not able to provide a repro project

**Comment by Gustash** [comment]
The license has been changed to LGPLv3 from 2.1.0 onwards. This means you are still required to make any changes you've made to the library public, but are no longer required to make the source code if your entire app public.

**Comment by Gustash** [comment]
@ejain you can submit that issue report now, your app is no longer required to be GPL'd with this change 🙂
