### ISSUE TITLE
iOS keyboard not working

### ISSUE THREAD

**Issue by afouchet** [Gustash/react-native-image-keyboard#9]
I installed react-native-image-keyboard, then cd ios, pod install,

But when I run the example app, I get the keyboard without the gif part

<img width="357" alt="Capture d’écran 2021-03-23 à 12 18 26" src="https://user-images.githubusercontent.com/7079913/112138875-53c8e580-8bd2-11eb-8b73-66cfbf215908.png">

How do I get a keyboard where I can select gif ?

**Comment by Gustash** [comment]
The iOS keyboard doesn't have that feature. You'd need to use Gboard

**Comment by fukemy** [comment]
tks, decided to removed that useless lib
